### Quiz

#### Part 1

Read in the dataset in `nutrition.csv` and display the first 5 rows of the dataset.

In [67]:
import pandas as pd

df = pd.read_csv("../data/nutrition.csv")
df.head(5)

         diet     calories  protein        BMI
0    omnivore  2199.053577   2.9 oz  28.23 BMI
1  vegetarian  2637.977586     64 g  24.59 bmi
2    omnivore  2052.026089   50.3 g   25.8 bmi
3   OtherDiet  2356.433560  128.1 g  26.39 bmi
4   OtherDiet  2885.355840   5.7 oz  24.11 BMI

#### Part 2

Drop any duplicate rows (rows where every value is the same).

In [68]:
df.drop_duplicates()

           diet     calories  protein        BMI
0      omnivore  2199.053577   2.9 oz  28.23 BMI
1    vegetarian  2637.977586     64 g  24.59 bmi
2      omnivore  2052.026089   50.3 g   25.8 bmi
3     OtherDiet  2356.433560  128.1 g  26.39 bmi
4     OtherDiet  2885.355840   5.7 oz  24.11 BMI
..          ...          ...      ...        ...
995      Veggie  2510.512521   2.7 oz  24.01 bmi
996    omnivore  2928.107440  140.5 g  19.93 BMI
997    omnivore  2232.056266   4.5 oz  30.14 BMI
998        Omni  1942.586928     92 g  24.26 BMI
999    omnivore  2133.716756   2.5 oz  30.72 BMI

[1000 rows x 4 columns]

#### Part 3

Treat any missing values for `calories` by replacing them with the mean of `calories`.

In [69]:
df["calories"]=df["calories"].fillna(df["calories"].mean())

#### Part 4

Do the following with the `protein` variable:

- Clean up the text
- Convert to `float`
- Convert to everything to ounces (1 oz is 28.3495 grams)

In [73]:
df["protein"].str.contains("g")
g_to_oz = 28.3495
mass_multiplier = (df["protein"].map(lambda boolean: g_to_oz if boolean else 1))
df["protein"] = (df["protein"].str.replace(" oz", "").str.replace(" g", "").astype("float")*mass_multiplier)

AttributeError: Can only use .str accessor with string values!

#### Part 5

Remove any unwanted text ("bmi" and "BMI") from the `BMI` variable and then convert this to a `float`.

In [ ]:
df["BMI"].str.replace(" bmi", "").str.replace(" BMI", "").astype("float")

#### Part 6

Standardize the categories in `diet` using the following mapping:

- Omni, omnivore → Omnivore
- other, OtherDiet → Other
- vegan, VGN → Vegan
- vegetarian, Veggie → Vegetarian

In [ ]:
diet_dict = {}
diet_dict["Omni"] = "Omnivore"
diet_dict["omnivore"] = "Omnivore"
diet_dict["other"] = "Other"
diet_dict["OtherDiet"] = "Other"
diet_dict["vegan"] = "Vegan"
diet_dict["VGN"] = "Vegan"
diet_dict["vegetarian"] = "Vegetarian"
diet_dict["Veggie"] = "Vegitarian"
df["diet"] = df["diet"].map(diet_dict)